[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Helix Framework"
authors = [{name = "Verdon", email = "verdon.crann@manchester.ac.uk"}]
dynamic = ["version", "description"]
